export enum Duration {
  _24HRS = '24HRS',
  Last7 = 'Last 7',
  Last30 = 'Last 30',
  Last90 = 'Last 90',
  TODAY = 'TODAY',
  DAY = 'DAY',
  WTD = 'WTD',
  WEEK = 'WEEK',
  MTD = 'MTD',
  MONTH = 'MONTH',
  QTD = 'QTD',
  _1Q = '1Q',
  _2Q = '2Q',
  _3Q = '3Q',
  _4Q = '4Q',
  YTD = 'YTD',
  LASTYEAR = 'LAST YEAR',
  LASTYEARQ1 = 'LAST YEAR Q1',
  LASTYEARQ2 = 'LAST YEAR Q2',
  LASTYEARQ3 = 'LAST YEAR Q3',
  LASTYEARQ4 = 'LAST YEAR Q4',
  _1Y = '1Y',
  _2Y = '2Y',
  CUSTOM = 'CUSTOM'
}
