name: ❔HowTo
description: Requirements and howto tickets
title: "❔[howto]: "
labels: ["howto","tbd","NEW"]
body:
- type: dropdown
  attributes:
    label: Target Release
    description: What version of platform 
    options:
      - PMFW 3.0.x (Default)
      - PMFW 3.1.x
      - PMFW 3.2.x
      - PMFW 3.3.x
      - PMFW 3.4.x
      - Other
- type: markdown
  attributes:
    value: |

      ----

- type: input
  id: os
  attributes:
    label: Usecase or HowTo Title
    description: "Describe the story and howto"
    placeholder: "e.g user assigns report view permission"
  validations:
    required: true  
- type: markdown
  attributes:
    value: |

      ----

- type: textarea
  id: php
  attributes:
    label: Screenshot and detail explainations
    description: "add mockups, screenshots and steps in case it is a howto"
  validations:
    required: true





