name: "Add-Open-Label"
on:
  issues:
    types:
      - assigned
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add labels
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["OPEN"]
            })

  remove_DONE_label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove labels
        uses: actions/github-script@v6
        with:
          script: |
            if (${{ contains(github.event.issue.labels.*.name, 'DONE') }}) {
              github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: ["DONE"]
              })
            }

  remove_QA_label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove labels
        uses: actions/github-script@v6
        with:
          script: |
            if (${{ contains(github.event.issue.labels.*.name, 'QA') }}) {
              github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: ["QA"]
              })
            }

  remove_OK_label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove labels
        uses: actions/github-script@v6
        with:
          script: |
            if (${{ contains(github.event.issue.labels.*.name, 'OK') }}) {
              github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: ["OK"]
              })
            }

  remove_NEW_label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove labels
        uses: actions/github-script@v6
        with:
          script: |
            if (${{ contains(github.event.issue.labels.*.name, 'NEW') }}) {
              github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: ["NEW"]
              })
            }


